### PR TITLE
fix: resolve `extends` where value is missing the filename part. eg `"extends": "@tsconfig/node14"`

### PR DESCRIPTION
**Pull request by Kingwl**
upstream: https://github.com/vitest-dev/vitest/issues/994 

And also need update in vite.

### CODE REVIEW

**Comment by dominikg** [comment]
workaround: add /tsconfig.json to your extends definition. 

This is also recommended in https://github.com/tsconfig/bases#readme

**Comment by dominikg** [comment]
package.json of `@tsconfig/node12` 

```
{"name":"@tsconfig/node12","repository":{"type":"git","url":"https://github.com/tsconfig/bases.git","directory":"bases"},"license":"MIT","description":"A base TSConfig for working with Node 12.","version":"1.0.9"}
```

as expected there is no "main" or exports map pointing at `tsconfig.json` inside. So it must be ts adding the filename when it's missing.

**Comment by Kingwl** [comment]
I have updated pr based on `src/compiler/commandLineParser.ts@getExtendsConfigPath` [here](https://github.com/microsoft/TypeScript/blob/main/src/compiler/commandLineParser.ts#L3023). 

The problem is I'm not sure how to pass this tests because I have added a tsconfig in `invalid`

**Comment by dominikg** [comment]
fixed in 1.2.1, thanks for this PR :heart:   loved that you added a test too.

**Pull request merged**
