### PR TITLE
fix(parse): fix edge cases for extends .. and nested extend

### LINKED ISSUE #149: `parse` function resolves `"extends": ".."` incorrectly
## Description

When the tsconfig.json has `"extends": ".."` and that pointed directory contains `package.json`. `parse` function resolves that to the main field. But TypeScript and `parseNative` function resolves that to `../tsconfig.json`.

## Reproduction
https://stackblitz.com/edit/node-k9hb7p?file=index.js

Running `tsc -p foo --showConfig` returns the resolved config by TypeScript.

## Additional Information

Output of `npx envinfo --system --binaries --browsers --npmPackages tsconfck` (Note: the command in the template (`npx envinfo --system --binaries --browsers --npmPackages "{tsconfck}"`) didn't include the tsconfck version number)
```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    tsconfck: ^3.0.0 => 3.0.0
```

### PR DESCRIPTION
**Pull request by dominikg**
fixes #149 

Adds special case handling for '..'. The test for it revealed another bug, namely that extended tsonfigs were parsed without parsing their extends , which lead to unextended return from cache.

To avoid eager deep extend parse, it checks if extends wasn't parsed and does it on first access

### CODE REVIEW

**Comment by dominikg** [comment]
this makes tsconfck a bit slower but more correct.

**Comment by dominikg** [comment]
@bluwy @sapphi-red  could need an eye or two here. Once released, vite needs to update its bundled tsconfck and unfortunately remove the direct cache access optimization here: https://github.com/vitejs/vite/blob/d2aa0969ee316000d3b957d7e879f001e85e369e/packages/vite/src/node/plugins/esbuild.ts#L451   so that nested extends is always resolved.

This does not affect many users today, it requires that  `a/b/tsconfig.json` extends  `a/tsconfig.json` extends `sometsconfig` and `a/foo.ts` being processed after`a/b/bar.ts`. 
But it is a sneaky issue as it does not error, it just returns the "unextended" `a/tsconfig.json` without the values from sometsconfig.

Note unlike mentioned in #149 i did not add fs checking, opting for a simpler special case, keeping the require.resolve. In my local benchmarking this was faster and is less code.

**Comment by bluwy** [comment]
> @bluwy @sapphi-red could need an eye or two here. Once released, vite needs to update its bundled tsconfck and unfortunately remove the direct cache access optimization here: [vitejs/vite@`d2aa096`/packages/vite/src/node/plugins/esbuild.ts#L451](https://github.com/vitejs/vite/blob/d2aa0969ee316000d3b957d7e879f001e85e369e/packages/vite/src/node/plugins/esbuild.ts#L451) so that nested extends is always resolved.

Seems fine to me. IIUC tsconfck's `parse()` also checks the cache first, so the perf difference isn't big.

---

WRT the fix. Is the fix only supporting `extends` one layer deeper? Or should it work recursively instead? I'm not too familiar with the code though.

**Comment by dominikg** [comment]
parseExtends works deep, but is only called eager for the first config in the chain. With the new check and lazy parseExtends the return of parse always has extended set and values merged.

the new nested fixture and additional expects in the cache test validate it.

**Pull request merged**
